name: Build and Push All Docker Images

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: corto-ui
            dockerfile: coffeeAGNTCY/coffee_agents/corto/docker/Dockerfile.ui
          - name: corto-exchange
            dockerfile: coffeeAGNTCY/coffee_agents/corto/docker/Dockerfile.exchange
          - name: corto-farm
            dockerfile: coffeeAGNTCY/coffee_agents/corto/docker/Dockerfile.farm
          - name: lungo-ui
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.ui
          - name: lungo-exchange
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.exchange
          - name: brazil-farm
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.brazil-farm
          - name: colombia-farm
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.colombia-farm
          - name: vietnam-farm
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.vietnam-farm
          - name: weather-mcp-server
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.weather-mcp
    permissions:
      packages: write
      contents: read

    steps:
      - name: Pre-cleanup Docker images
        run: docker system prune -af

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git tag (if any)
        id: get_tag
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Log Event Type
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Tag: ${{ steps.get_tag.outputs.tag_name }}"

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (PR)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/coffee-agntcy/${{ matrix.image.name }}:pr-${{ github.event.pull_request.number }}

      - name: Build and push Docker image (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/coffee-agntcy/${{ matrix.image.name }}:latest

      - name: Build and push Docker image (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/coffee-agntcy/${{ matrix.image.name }}:${{ steps.get_tag.outputs.tag_name }}
